// Photo per curated category for the homepage "Shop by category" grid. Kept
// separate from categories.ts because that file is AUTO-GENERATED by the
// catalogue transform script and would overwrite any edits. CategoryGrid shows
// the image when a mapping exists, else falls back to the line icon.
export const CATEGORY_IMAGES: Record<string, string> = {
  caravan: "/home/caravan.jpg",
  joint: "/home/windows.jpg",
  fire: "/home/fire.jpg",
  ewi: "/home/ewi.jpg",
  fixing: "/home/floor.jpg",
  water: "/home/wet.jpg",
  primers: "/home/primers.jpg",
};
